const key = 'mi-tutora:projects:v1';
const userKey = (uid) => uid ? `${key}:${uid}` : key;
const emptyState = () => ({ status: 'not-started', languageId: null, currentCheckpoint: 0, completedCheckpoints: [], guideState: {}, workspace: null, createdAt: null, updatedAt: null, attempts: 0, validationStatus: 'idle', completedAt: null, score: 0, revision: 0 });
export class ProjectProgressService {
  constructor({ storage, repositoryFactory = null, debounceMs = 900 } = {}) { this.storage = storage; this.repositoryFactory = repositoryFactory; this.debounceMs = debounceMs; this.repository = null; this.uid = null; this.revisions = new Map(); this.timers = new Map(); this.generations = new Map(); this.listeners = new Map(); this.statuses = new Map(); this.inFlight = new Map(); }
  connect(uid, repositoryFactory = this.repositoryFactory) { if (this.uid === uid && this.repository) return; const previousUid = this.uid; this.cancelAll(); this.uid = uid ?? null; this.repositoryFactory = repositoryFactory; this.repository = uid && repositoryFactory ? repositoryFactory(uid) : null; this.revisions.clear(); this.statuses.clear(); if (this.uid && previousUid === null) this.migrateLegacyCache(this.uid); }
  storageKey() { return userKey(this.uid); }
  migrateLegacyCache(uid) { const target = userKey(uid); const storage = this.storage ?? globalThis.localStorage; try { if (!storage?.getItem(target) && storage?.getItem(key)) { storage.setItem(target, storage.getItem(key)); storage.removeItem?.(key); } } catch { /* Local recovery is best effort. */ } }
  read() { try { return JSON.parse((this.storage ?? globalThis.localStorage)?.getItem(this.storageKey())) ?? {}; } catch { return {}; } }
  write(all) { (this.storage ?? globalThis.localStorage)?.setItem(this.storageKey(), JSON.stringify(all)); }
  get(projectId) { const stored = this.read()[projectId]; return stored ? { ...emptyState(), ...stored, status: stored.status === 'started' ? 'active' : stored.status } : emptyState(); }
  cache(projectId, state) { const all = this.read(); all[projectId] = state; this.write(all); return state; }
  emit(projectId, status, error = null) { const event = { status, error }; this.statuses.set(projectId, event); for (const listener of this.listeners.get(projectId) ?? []) listener(event); }
  subscribe(projectId, listener) { const listeners = this.listeners.get(projectId) ?? new Set(); listeners.add(listener); this.listeners.set(projectId, listeners); listener(this.statuses.get(projectId) ?? { status: 'saved', error: null }); return () => listeners.delete(listener); }
  async hydrate(projectId) { const local = this.get(projectId); if (!this.repository) return local; this.emit(projectId, 'loading'); try { const cloud = await this.repository.load(projectId); if (cloud) { this.revisions.set(projectId, cloud.revision); this.cache(projectId, { ...local, ...cloud }); this.emit(projectId, 'saved'); return this.get(projectId); } if (local.status !== 'not-started') { const migrated = await this.repository.save(projectId, local, 0); this.revisions.set(projectId, migrated.revision); this.cache(projectId, { ...local, ...migrated }); this.emit(projectId, 'saved'); return this.get(projectId); } this.revisions.set(projectId, 0); this.emit(projectId, 'saved'); return local; } catch (error) { this.emit(projectId, 'error', error); return local; } }
  update(projectId, partial, { save = true, immediate = false } = {}) { const next = this.cache(projectId, { ...this.get(projectId), ...partial, updatedAt: new Date().toISOString() }); if (save) this.scheduleSave(projectId, { immediate }); return next; }
  scheduleSave(projectId, { immediate = false } = {}) { if (!this.repository) return; clearTimeout(this.timers.get(projectId)); this.emit(projectId, 'saving'); const generation = this.generations.get(projectId) ?? 0; if (immediate) void this.saveNow(projectId, generation).catch(() => {}); else this.timers.set(projectId, setTimeout(() => void this.saveNow(projectId, generation).catch(() => {}), this.debounceMs)); }
  saveNow(projectId, generation = this.generations.get(projectId) ?? 0) { clearTimeout(this.timers.get(projectId)); this.timers.delete(projectId); const pending = (this.inFlight.get(projectId) ?? Promise.resolve()).catch(() => {}).then(() => this.performSave(projectId, generation)); this.inFlight.set(projectId, pending); return pending.finally(() => { if (this.inFlight.get(projectId) === pending) this.inFlight.delete(projectId); }); }
  async performSave(projectId, generation) { const repository = this.repository; if (!repository || generation !== (this.generations.get(projectId) ?? 0)) return this.get(projectId); try { const saved = await repository.save(projectId, this.get(projectId), this.revisions.get(projectId) ?? 0); if (repository !== this.repository || generation !== (this.generations.get(projectId) ?? 0)) return this.get(projectId); this.revisions.set(projectId, saved.revision); const next = this.cache(projectId, { ...this.get(projectId), revision: saved.revision, schemaVersion: saved.schemaVersion }); this.emit(projectId, 'saved'); return next; } catch (error) { if (repository !== this.repository || generation !== (this.generations.get(projectId) ?? 0)) return this.get(projectId); this.emit(projectId, error?.code === 'projects/conflict' ? 'conflict' : 'error', error); throw error; } }
  retry(projectId) { this.emit(projectId, 'saving'); return this.saveNow(projectId); }
  cancel(projectId) { clearTimeout(this.timers.get(projectId)); this.timers.delete(projectId); this.generations.set(projectId, (this.generations.get(projectId) ?? 0) + 1); }
  cancelAll() { for (const projectId of new Set([...this.timers.keys(), ...this.inFlight.keys(), ...this.generations.keys()])) this.cancel(projectId); }
  flush(projectId) { if (this.timers.has(projectId)) return this.saveNow(projectId); return (this.inFlight.get(projectId) ?? Promise.resolve()).then(() => this.get(projectId)); }
  start(projectId, languageId) { const current = this.get(projectId); if (!languageId && current.languageId) return current; const now = new Date().toISOString(); return this.update(projectId, { status: current.status === 'completed' ? 'completed' : 'active', languageId: languageId ?? current.languageId, createdAt: current.createdAt ?? now, startedAt: current.startedAt ?? now }, { immediate: true }); }
  resetForLanguage(projectId, languageId) { this.cancel(projectId); const now = new Date().toISOString(); const next = this.cache(projectId, { ...emptyState(), status: 'active', languageId, createdAt: now, updatedAt: now, startedAt: now }); this.scheduleSave(projectId, { immediate: true }); return next; }
  completeCheckpoint(projectId, checkpointId, checkpointIndex, checkpointCount) { const current = this.get(projectId); const completedCheckpoints = [...new Set([...current.completedCheckpoints, checkpointId])]; const complete = completedCheckpoints.length >= checkpointCount; return this.update(projectId, { completedCheckpoints, currentCheckpoint: complete ? checkpointIndex : Math.min(checkpointIndex + 1, checkpointCount - 1), status: complete ? 'completed' : 'active', completedAt: complete ? current.completedAt ?? new Date().toISOString() : null }, { immediate: true }); }
  visitPage(projectId, pageIndex) { const current = this.get(projectId); return this.update(projectId, { lastPageIndex: Math.max(current.lastPageIndex ?? 0, pageIndex), previewedPages: [...new Set([...(current.previewedPages ?? []), pageIndex])] }); }
  saveWorkspace(projectId, files, entryFilePath, folders = [], options) { return this.update(projectId, { files, folders, entryFilePath, workspace: { files, folders, entryFilePath }, submission: files?.[entryFilePath]?.content ?? this.get(projectId).submission }, options); }
  recordValidation(projectId, result, submission) { const current = this.get(projectId); return this.update(projectId, { attempts: current.attempts + 1, validationStatus: result.passed ? 'passed' : 'failed', score: Math.max(current.score, result.score ?? 0), submission: result.passed ? submission : current.submission, ...result.passed && !current.languageId ? { status: 'completed', completedAt: current.completedAt ?? new Date().toISOString() } : {} }, { immediate: result.passed }); }
}
export const projectProgressService = new ProjectProgressService();
