import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { deleteApp, initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { cleanupExpiredCompilerPublicData, cleanupExpiredRateLimits, createFeedback, createShare, enforceRateLimit, readShare } from '../../server/compiler-public/compilerPublicService.js';
import { PublicRemoteCompilerQuota, cleanupExpiredPublicRemoteQuotas } from '../../server/remote-compiler/PublicRemoteCompilerQuota.js';
import { createPublicRemoteCompilerHandler } from '../../server/remote-compiler/publicRemoteCompilerHandler.js';

const projectId=process.env.FIREBASE_PROJECT_ID||'demo-compiler-public'; let app; let authApp; let db; let auth; const now=Date.UTC(2026,8,25,12);
const request=(headers={})=>({headers,socket:{remoteAddress:'127.0.0.1'}});
beforeAll(()=>{app=initializeApp({projectId},`acceptance-${Date.now()}`);authApp=initializeApp({projectId:process.env.COMPILER_PUBLIC_AUTH_PROJECT_ID||projectId},`acceptance-auth-${Date.now()}`);db=getFirestore(app);auth=getAuth(authApp);});
afterAll(async()=>{for(const name of ['compilerShares','compilerFeedback','compilerPublicRateLimits','compilerPublicRemoteRateLimits','compilerPublicRemoteRuntime']){const snapshot=await db.collection(name).get();const batch=db.batch();snapshot.docs.forEach((doc)=>batch.delete(doc.ref));if(!snapshot.empty)await batch.commit();}await deleteApp(authApp);await deleteApp(app);});

describe('real Firestore emulator acceptance',()=>{
  it('creates and reads an immutable anonymous share with 30-day expiry',async()=>{const created=await createShare({db,auth,request:request(),body:{languageId:'python',source:'print("exact")',ownerUid:'spoof'},now});expect(created.shareId).toMatch(/^[A-Za-z0-9_-]{22}$/);const stored=(await db.collection('compilerShares').doc(created.shareId).get()).data();expect(stored).toEqual(expect.objectContaining({ownerUid:null,source:'print("exact")',stdin:null,status:'active',sourceBytes:14}));expect(stored.expiresAt.toMillis()-now).toBe(30*24*60*60*1000);const publicValue=await readShare({db,shareId:created.shareId,now});expect(publicValue.ownerUid).toBeUndefined();});
  it('enforces transactional concurrent limits and hourly rollover',async()=>{const key=`concurrent-${Date.now()}`;await Promise.all(Array.from({length:10},()=>enforceRateLimit(db,{scope:'acceptance',key,limit:10,now})));await expect(enforceRateLimit(db,{scope:'acceptance',key,limit:10,now})).rejects.toMatchObject({status:429});await expect(enforceRateLimit(db,{scope:'acceptance',key,limit:10,now:now+3600000})).resolves.toBeUndefined();});
  it('enforces public remote per-identity/global leases transactionally and recovers stale work',async()=>{let clock=now;const quota=new PublicRemoteCompilerQuota({db,now:()=>clock,policy:{leaseMs:100}});const first=await quota.acquire({identity:'acceptance-same',authenticated:false,language:'go'});await expect(quota.acquire({identity:'acceptance-same',authenticated:false,language:'rust'})).rejects.toMatchObject({code:'compiler/public-concurrency-limit'});await quota.release(first);const leases=await Promise.all(Array.from({length:12},(_,index)=>quota.acquire({identity:`acceptance-global-${index}`,authenticated:false,language:'go'})));await expect(quota.acquire({identity:'acceptance-global-overflow',authenticated:false,language:'go'})).rejects.toMatchObject({code:'compiler/runner-busy'});clock+=101;await expect(quota.acquire({identity:'acceptance-global-overflow',authenticated:false,language:'rust'})).resolves.toBeTruthy();await Promise.all(leases.map((lease)=>quota.release(lease)));});
  it('cleans expired public remote quota documents in a bounded batch',async()=>{const collection=db.collection('compilerPublicRemoteRateLimits');await collection.doc('expired-cleanup').set({expiresAt:now-1});await collection.doc('live-cleanup').set({expiresAt:now+1000});expect(await cleanupExpiredPublicRemoteQuotas(db,now,1)).toEqual({deleted:1});expect((await collection.doc('live-cleanup').get()).exists).toBe(true);});
  it('verifies a real Auth emulator token and ignores spoofed ownership',async()=>{const uid=`acceptance-${Date.now()}`;const customToken=await auth.createCustomToken(uid);const authHost=process.env.FIREBASE_AUTH_EMULATOR_HOST||'127.0.0.1:9099';const response=await fetch(`http://${authHost}/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=fake-api-key`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:customToken,returnSecureToken:true})});const user=await response.json();expect(response.ok).toBe(true);await expect(auth.verifyIdToken(user.idToken)).resolves.toEqual(expect.objectContaining({uid}));const created=await createShare({db,auth,request:request({authorization:`Bearer ${user.idToken}`}),body:{languageId:'javascript',source:'console.log(1)',ownerUid:'spoofed'},now});const stored=(await db.collection('compilerShares').doc(created.shareId).get()).data();expect(stored.ownerUid).toBe(uid);expect((await readShare({db,shareId:created.shareId,now})).ownerUid).toBeUndefined();});
  it('executes the public endpoint with a real emulator token and a UID-derived quota identity',async()=>{const uid=`remote-${Date.now()}`;const customToken=await auth.createCustomToken(uid);const authHost=process.env.FIREBASE_AUTH_EMULATOR_HOST||'127.0.0.1:9099';const signIn=await fetch(`http://${authHost}/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=fake-api-key`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:customToken,returnSecureToken:true})});const user=await signIn.json();const quota=new PublicRemoteCompilerQuota({db,now:()=>now});let acquired;const originalAcquire=quota.acquire.bind(quota);quota.acquire=async(input)=>{acquired=input;return originalAcquire(input);};const handler=createPublicRemoteCompilerHandler({environment:{PUBLIC_REMOTE_COMPILER_ENABLED:'true',REMOTE_COMPILER_RUNTIME_ENABLED:'true',REMOTE_COMPILER_DISTRIBUTED_QUOTA_ENABLED:'true',GO_RUNTIME_ENABLED:'true',RUST_RUNTIME_ENABLED:'true'},authenticator:{authenticate:async(req)=>{const token=String(req.headers.authorization).slice(7);return auth.verifyIdToken(token);}},credentialFactory:()=>({preflight:async()=>{}}),quotaFactory:async()=>({quota,close:async()=>{}}),runner:{execute:async()=>({status:'success',stdout:'Hello\n',stderr:'',exitCode:0})},logger:{info:()=>{}}});const req={method:'POST',headers:{authorization:`Bearer ${user.idToken}`},socket:{remoteAddress:'127.0.0.1'},body:{languageId:'go',source:'package main\nfunc main(){}',stdin:'',uid:'spoofed'}};const res={writableEnded:false,setHeader(){},status(value){this.statusCode=value;return this;},json(value){this.body=value;this.writableEnded=true;return this;}};await handler(req,res);expect(res.statusCode).toBe(400);expect(acquired).toBeUndefined();delete req.body.uid;res.writableEnded=false;await handler(req,res);expect(res.statusCode).toBe(200);expect(acquired).toEqual(expect.objectContaining({identity:uid,authenticated:true}));});
  it('returns the same not-found result for unknown, expired, and removed shares',async()=>{for(const [id,data] of [['AAAAAAAAAAAAAAAAAAAAAA',{status:'active',expiresAt:Timestamp.fromMillis(now-1)}],['BBBBBBBBBBBBBBBBBBBBBB',{status:'removed',expiresAt:Timestamp.fromMillis(now+1000)}]])await db.collection('compilerShares').doc(id).set({schemaVersion:1,languageId:'python',source:'',stdinIncluded:false,stdin:null,createdAt:Timestamp.fromMillis(now),...data});for(const id of ['CCCCCCCCCCCCCCCCCCCCCC','AAAAAAAAAAAAAAAAAAAAAA','BBBBBBBBBBBBBBBBBBBBBB'])await expect(readShare({db,shareId:id,now})).rejects.toMatchObject({status:404,code:'compiler-share/not-found'});});
  it('persists only allowlisted feedback context and no injected private fields',async()=>{await createFeedback({db,auth,request:request(),body:{type:'bug',description:'Acceptance feedback',languageId:'python',route:'/python',source:'secret',stdin:'secret',email:'secret',uid:'spoof',context:{theme:'dark',userAgent:'x'.repeat(700),source:'secret',viewportWidth:99999,viewportHeight:-1}},now});const docs=await db.collection('compilerFeedback').get();const stored=docs.docs.at(-1).data();expect(stored.userUid).toBeNull();expect(stored.context.userAgent).toHaveLength(500);expect(stored.context.viewportWidth).toBe(10000);expect(stored.context.viewportHeight).toBe(0);expect(JSON.stringify(stored)).not.toContain('secret');expect(stored.source).toBeUndefined();});
  it('cleans expired shares and rate buckets in independent bounded batches',async()=>{
    for(const name of ['compilerShares','compilerPublicRateLimits']){const snapshot=await db.collection(name).get();for(let offset=0;offset<snapshot.docs.length;offset+=400){const batch=db.batch();snapshot.docs.slice(offset,offset+400).forEach((doc)=>batch.delete(doc.ref));await batch.commit();}}
    const write=async(entries)=>{for(let offset=0;offset<entries.length;offset+=400){const batch=db.batch();entries.slice(offset,offset+400).forEach(([ref,data])=>batch.set(ref,data));await batch.commit();}};
    const expiredShares=Array.from({length:255},(_,index)=>[db.collection('compilerShares').doc(`expired-${index}`),{schemaVersion:1,languageId:'python',source:'',stdinIncluded:false,stdin:null,status:'active',createdAt:Timestamp.fromMillis(now-1000),expiresAt:Timestamp.fromMillis(now-1)}]);
    const liveShares=Array.from({length:4},(_,index)=>[db.collection('compilerShares').doc(`live-${index}`),{schemaVersion:1,languageId:'python',source:'',stdinIncluded:false,stdin:null,status:'active',createdAt:Timestamp.fromMillis(now),expiresAt:Timestamp.fromMillis(now+60000)}]);
    const expiredRates=Array.from({length:205},(_,index)=>[db.collection('compilerPublicRateLimits').doc(`expired-rate-${index}`),{scope:'share',count:1,windowStart:Timestamp.fromMillis(now-10000),expiresAt:Timestamp.fromMillis(now-1)}]);
    const liveRates=Array.from({length:3},(_,index)=>[db.collection('compilerPublicRateLimits').doc(`live-rate-${index}`),{scope:'share',count:1,windowStart:Timestamp.fromMillis(now),expiresAt:Timestamp.fromMillis(now+60000)}]);
    await write([...expiredShares,...liveShares,...expiredRates,...liveRates]);
    expect(await cleanupExpiredCompilerPublicData(db,now)).toEqual({deleted:200});
    expect(await cleanupExpiredRateLimits(db,now)).toEqual({deleted:200});
    expect(await cleanupExpiredCompilerPublicData(db,now)).toEqual({deleted:55});
    expect(await cleanupExpiredRateLimits(db,now)).toEqual({deleted:5});
    expect((await db.collection('compilerShares').where('expiresAt','>',Timestamp.fromMillis(now)).get()).size).toBe(4);
    expect((await db.collection('compilerPublicRateLimits').where('expiresAt','>',Timestamp.fromMillis(now)).get()).size).toBe(3);
  });
});
