export const dashboardNavigation = [
  { id: 'learn', label: 'Learn', icon: 'learn' },
  { id: 'my-courses', label: 'My Courses', icon: 'courses' },
  { id: 'practice', label: 'Practice', icon: 'practice' },
  { id: 'projects', label: 'Projects', icon: 'projects', comingSoon: true },
  { id: 'challenges', label: 'Challenges', icon: 'challenges', comingSoon: true },
  { id: 'bookmarks', label: 'Bookmarks', icon: 'bookmarks' },
  { id: 'certificates', label: 'Certificates', icon: 'certificates', comingSoon: true },
  { id: 'settings', label: 'Settings', icon: 'settings' },
];

export const courseCategories = [
  { id: 'programming', label: 'Programming', description: 'Build software and problem-solving skills', icon: 'code', count: 28 },
  { id: 'school', label: 'School Subjects', description: 'Master concepts at your own pace', icon: 'school', count: 34 },
  { id: 'languages', label: 'Languages', description: 'Communicate with confidence', icon: 'languages', count: 16 },
  { id: 'technology', label: 'Technology', description: 'Understand modern digital tools', icon: 'technology', count: 21 },
  { id: 'interview', label: 'Interview Preparation', description: 'Prepare for your next opportunity', icon: 'interview', count: 12 },
];

export const dashboardCourses = [
  {
    id: 'python',
    name: 'Python Foundations',
    description: 'Learn core Python concepts through concise lessons and practical exercises.',
    category: 'programming',
    difficulty: 'Beginner',
    duration: '5h 40m',
    progress: 24,
    badge: 'Continue',
    thumbnail: 'python',
    available: true,
  },
  {
    id: 'web-development',
    name: 'Modern Web Development',
    description: 'Create responsive interfaces with HTML, CSS, and JavaScript.',
    category: 'programming',
    difficulty: 'Beginner',
    duration: '8h 15m',
    progress: 0,
    badge: 'Popular',
    thumbnail: 'web',
  },
  {
    id: 'data-structures',
    name: 'Data Structures',
    description: 'Develop a practical mental model for efficient data organization.',
    category: 'technology',
    difficulty: 'Intermediate',
    duration: '6h 30m',
    progress: 0,
    thumbnail: 'data',
  },
  {
    id: 'spoken-english',
    name: 'Confident English',
    description: 'Improve everyday speaking, vocabulary, and listening fluency.',
    category: 'languages',
    difficulty: 'Beginner',
    duration: '4h 20m',
    progress: 12,
    badge: 'New',
    thumbnail: 'language',
  },
  {
    id: 'algebra-essentials',
    name: 'Algebra Essentials',
    description: 'Turn equations and functions into intuitive, reusable tools.',
    category: 'school',
    difficulty: 'Beginner',
    duration: '5h 10m',
    progress: 38,
    thumbnail: 'math',
  },
  {
    id: 'frontend-interviews',
    name: 'Frontend Interview Lab',
    description: 'Practice common UI engineering questions and coding patterns.',
    category: 'interview',
    difficulty: 'Intermediate',
    duration: '3h 45m',
    progress: 0,
    badge: 'Trending',
    thumbnail: 'interview',
  },
  {
    id: 'ai-literacy',
    name: 'Practical AI Literacy',
    description: 'Understand AI systems, prompting, limitations, and responsible use.',
    category: 'technology',
    difficulty: 'Beginner',
    duration: '2h 50m',
    progress: 0,
    badge: 'Featured',
    thumbnail: 'ai',
  },
  {
    id: 'javascript-patterns',
    name: 'JavaScript Patterns',
    description: 'Write maintainable JavaScript using modern language patterns.',
    category: 'programming',
    difficulty: 'Intermediate',
    duration: '4h 55m',
    progress: 7,
    thumbnail: 'javascript',
  },
];

export const dashboardSections = [
  {
    id: 'featured',
    eyebrow: 'Curated by MiTutora',
    title: 'Featured courses',
    description: 'Structured paths designed to build useful skills.',
    courseIds: ['python', 'ai-literacy', 'frontend-interviews'],
  },
  {
    id: 'recommended',
    eyebrow: 'Picked for you',
    title: 'Recommended courses',
    description: 'Based on your learning preferences and current level.',
    courseIds: ['web-development', 'spoken-english', 'data-structures', 'javascript-patterns'],
  },
  {
    id: 'recent',
    eyebrow: 'Jump back in',
    title: 'Recently viewed',
    description: 'Continue exploring where you last left off.',
    courseIds: ['algebra-essentials', 'javascript-patterns', 'python'],
  },
  {
    id: 'my-courses',
    eyebrow: 'Your library',
    title: 'My courses',
    description: 'Courses currently saved to your learning plan.',
    courseIds: ['python', 'algebra-essentials', 'spoken-english'],
  },
];
