import { useMemo, useState } from 'react';
import { projectCatalog } from '../repositories/ProjectCatalog';
import { ProjectCard } from '../components/ProjectCard';
import { ProjectDetails } from './ProjectDetails';
import { ProjectWorkspace } from './ProjectWorkspace';
import { projectProgressService } from '../services/ProjectProgressService';
export function ProjectsPage() {
  const projects = projectCatalog.getProjects(); const [filters, setFilters] = useState({ language: 'all', category: 'all' }); const [selected, setSelected] = useState(null); const [screen, setScreen] = useState('catalog'); const [, refresh] = useState(0);
  const visible = useMemo(() => projects.filter((project) => (filters.language === 'all' || project.language === filters.language) && (filters.category === 'all' || project.category === filters.category)), [filters, projects]);
  if (selected && screen === 'details') return <ProjectDetails project={selected} progress={projectProgressService.get(selected.id)} onBack={() => { setSelected(null); setScreen('catalog'); }} onStart={() => { projectProgressService.start(selected.id); setScreen('workspace'); }} />;
  if (selected && screen === 'workspace') return <ProjectWorkspace project={selected} onBack={() => setScreen('details')} onProgress={() => refresh((value) => value + 1)} />;
  return <div className="projects-page"><header><h1>Build projects you can keep.</h1><p>Implement focused Python utilities, validate them against controlled tests, and export complete repositories.</p></header><section className="project-levels" aria-label="Project difficulty"><button className="is-active" type="button">Easy</button><button disabled type="button">Intermediate <small>Coming Soon</small></button><button disabled type="button">Advanced <small>Coming Soon</small></button></section><section className="project-filters" aria-label="Project filters"><label>Language<select value={filters.language} onChange={(event) => setFilters((current) => ({ ...current, language: event.target.value }))}><option value="all">All languages</option><option value="python">Python</option></select></label><label>Category<select value={filters.category} onChange={(event) => setFilters((current) => ({ ...current, category: event.target.value }))}><option value="all">All categories</option><option value="Python Fundamentals">Python Fundamentals</option></select></label></section><section className="project-catalog" aria-labelledby="project-catalog-title"><div><h2 id="project-catalog-title">Easy Projects</h2><p>{visible.length} projects available</p></div><div className="project-grid">{visible.map((project) => <ProjectCard key={project.id} project={project} progress={projectProgressService.get(project.id)} onOpen={(next) => { setSelected(next); setScreen('details'); }} />)}</div></section></div>;
}
