import { useMemo, useRef, useState } from 'react';
import { ArrowLeft, CheckCircle2, Download, Play } from 'lucide-react';
import { EditorPlaceholder } from '../../components/EditorPlaceholder';
import { useCompilerManager } from '../../compiler/CompilerProvider';
import { ProjectValidator } from '../validation/ProjectValidator';
import { ProjectTestResults } from '../components/ProjectTestResults';
import { projectExporter } from '../export/ProjectExporter';
import { projectProgressService } from '../services/ProjectProgressService';
export function ProjectWorkspace({ project, onBack, onProgress }) {
  const manager = useCompilerManager(); const validator = useMemo(() => new ProjectValidator(manager), [manager]);
  const progress = projectProgressService.get(project.id); const [code, setCode] = useState(progress.submission ?? project.starterCode); const [result, setResult] = useState(null); const [running, setRunning] = useState(false); const controller = useRef(null);
  const completed = progress.status === 'completed' || result?.passed;
  const validate = async () => { controller.current?.abort(); controller.current = new AbortController(); setRunning(true); setResult(null); try { const next = await validator.validateProject(project, code, { signal: controller.current.signal }); setResult(next); onProgress(projectProgressService.recordValidation(project.id, next, code)); } catch (error) { if (error.name !== 'AbortError') setResult({ passed: false, tests: [], score: 0, errors: [error.message] }); } finally { setRunning(false); } };
  return <div className="project-workspace-page"><header><button className="practice-back-button" type="button" onClick={onBack}><ArrowLeft /> Project details</button><div><span>Build · {project.language}</span><h1>{project.title}</h1><p>{project.instructions}</p></div></header><div className="project-workspace-grid"><article className="project-brief"><h2>Requirements</h2><ul>{project.requirements.map((item) => <li key={item}>{item}</li>)}</ul><h2>Function contract</h2><code>{project.functionDefinition.name}({project.functionDefinition.parameters.join(', ')}) → {project.functionDefinition.returns}</code><h2>Example</h2><p><strong>Input</strong> <code>{project.example.input}</code></p><p><strong>Output</strong> <code>{project.example.output}</code></p></article><section className="project-editor-card" aria-label="Your implementation"><header><div><span>Your Implementation</span><strong>{project.template.sourcePath}</strong></div><button className="button button--secondary" type="button" onClick={() => { setCode(project.starterCode); setResult(null); }}>Reset</button></header><EditorPlaceholder editor={{ ariaLabel: `${project.title} implementation editor` }} value={code} onChange={(value) => { setCode(value); setResult(null); }} /><footer><button className="button button--primary" type="button" disabled={running} onClick={validate}><Play /> {running ? 'Validating…' : 'Validate Project'}</button></footer></section></div><ProjectTestResults result={result} />{completed ? <section className="project-complete" role="status"><CheckCircle2 /><div><span>Project Complete</span><h2>Your implementation passed all required tests.</h2><p>Export a clean repository containing your implementation, README, setup files, and public tests.</p></div><button className="button button--primary" type="button" onClick={() => projectExporter.download(project, code)}><Download /> Export Project</button></section> : null}</div>;
}
