export const detectorConfig = Object.freeze({
  inference: Object.freeze({
    intervalMs: 350,
    wasmPath: 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm',
    faceModelPath: 'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',
    objectModelPath: 'https://storage.googleapis.com/mediapipe-models/object_detector/efficientdet_lite0/int8/1/efficientdet_lite0.tflite',
    delegate: 'GPU',
    maxFaces: 3,
    minFaceDetectionConfidence: 0.5,
    minFacePresenceConfidence: 0.5,
    minTrackingConfidence: 0.5,
    minObjectScoreThreshold: 0.35,
  }),
  facePresence: Object.freeze({
    minDetectionConfidence: 0.5,
    violationPersistenceMs: 1500,
    recoveryPersistenceMs: 750,
    stabilitySampleCount: 12,
  }),
  headPose: Object.freeze({
    yawThresholdDegrees: 24,
    pitchThresholdDegrees: 20,
    rollThresholdDegrees: 28,
  }),
  lookingAway: Object.freeze({
    gracePeriodMs: 2000,
    recoveryPersistenceMs: 750,
  }),
  phone: Object.freeze({
    categoryNames: Object.freeze(['cell phone', 'mobile phone', 'phone']),
    minimumConfidence: 0.52,
    minimumVisibleArea: 0.002,
    minimumPersistence: 1200,
    maximumLostFrames: 4,
    cameraDistanceCompensation: 0.65,
    confidenceSmoothing: 0.35,
    detectionWindow: 8,
    modelVersion: 'phone-calibration-v2',
    confidenceThreshold: 0.52,
    violationPersistenceMs: 1200,
    recoveryPersistenceMs: 1000,
  }),
  objects: Object.freeze({
    minimumConfidence: 0.5,
    minimumPersistence: 1500,
    maximumLostFrames: 3,
    detectionWindow: 6,
    supportedCategories: Object.freeze({
      phone: Object.freeze(['cell phone']),
      book: Object.freeze(['book']),
    }),
    unsupportedCategories: Object.freeze(['tablet', 'notebook', 'printed papers', 'calculator']),
    modelVersion: 'efficientdet-lite0-coco-v1',
  }),
  lighting: Object.freeze({
    minimumBrightness: 55,
    maximumBrightness: 210,
    idealBrightnessRange: Object.freeze([95, 175]),
    samplingInterval: 350,
    smoothingWindow: 8,
  }),
  background: Object.freeze({
    samplingInterval: 350,
    smoothingWindow: 8,
    blockedBrightness: 12,
    minimumContrast: 8,
    acceptableMotion: 18,
    excessiveMotion: 38,
    minimumConfidence: 35,
  }),
  audio: Object.freeze({
    minimumVoiceDuration: 2000,
    warningDuration: 6000,
    violationDuration: 12000,
    noiseThreshold: 0.22,
    silenceThreshold: 0.035,
    samplingInterval: 200,
    fftSize: 1024,
    smoothingWindow: 8,
    probabilitySmoothingWindow: 6,
    speechConfidence: 0.58,
    noiseConfidence: 0.62,
    noiseEnergyReference: 0.18,
    sampleRate: 16000,
    frameSamples: 512,
    wasmThreads: 1,
    modelVersion: 'silero-vad-v5',
    modelChecksum: '2623a2953f6ff3d2c1e61740c6cdb7168133479b267dfef114a4a3cc5bdd788f',
    modelLoadTimeout: 15000,
    maxRetries: 3,
    retryDelay: 500,
    backoffFactor: 2,
    healthCheckInterval: 3000,
    inferenceTimeout: 5000,
    staleInferenceTimeout: 10000,
    bufferSize: 2048,
    analyserSmoothing: 0.3,
    speechPersistence: 2500,
    conversationDuration: 8000,
    conversationRecoveryTimeout: 1800,
    otherSpeakerConfidence: 0.72,
    remoteSpeechMaxLevel: 0.055,
    musicConfidence: 0.7,
    mediaConfidence: 0.68,
    mediaPersistence: 4000,
    typingConfidence: 0.7,
    typingMinimumTransients: 5,
    typingWindow: 2500,
    typingPersistence: 1500,
    transientCrestFactor: 4.5,
    transientZeroCrossingRate: 0.12,
    loudNoiseMultiplier: 4,
    saturatedLevel: 0.92,
    clippingRatio: 0.08,
    zeroInputLevel: 0.0005,
    zeroInputDuration: 4000,
    unknownConfidence: 0.35,
    acousticSmoothingWindow: 8,
    adaptiveLearningRate: 0.04,
    adaptiveMinimumSamples: 20,
    initialNoiseFloor: 0.012,
    featureVersion: 'acoustic-features-v1',
  }),
});
