const pythonProject = (definition) => Object.freeze({
  difficulty: 'Easy',
  language: 'python',
  category: 'Python Fundamentals',
  estimatedMinutes: 35,
  allowedImports: [],
  validation: { type: 'python-function', tests: definition.tests },
  template: { sourcePath: `src/${definition.moduleName}.py`, testPath: `tests/test_${definition.moduleName}.py` },
  export: { repositoryName: definition.slug },
  ...definition,
});

export const easyProjects = Object.freeze([
  pythonProject({
    id: 'simple-calculator', slug: 'simple-calculator', title: 'Simple Calculator',
    description: 'Build a dependable calculator for the four everyday arithmetic operations.',
    why: 'A calculator is a compact way to practice turning user choices into safe, predictable program behavior.',
    moduleName: 'simple_calculator', estimatedMinutes: 25,
    skills: ['Functions', 'Conditionals', 'Arithmetic', 'Error handling'],
    learningObjectives: ['Choose an operation with conditionals.', 'Return calculated values from a function.', 'Handle unsupported operations safely.'],
    instructions: 'Implement calculate to apply +, -, *, or /. Return None for an unsupported operator or division by zero.',
    requirements: ['Support addition, subtraction, multiplication, and division.', 'Return None instead of crashing on division by zero.', 'Return None for unsupported operators.', 'Do not change the function signature.'],
    example: { input: '8, 2, "/"', output: '4.0' },
    functionDefinition: { name: 'calculate', parameters: ['left', 'right', 'operator'], returns: 'number | None' },
    starterCode: 'def calculate(left, right, operator):\n    """Apply a supported arithmetic operation safely."""\n    # TODO: implement the calculator logic\n',
    tests: [
      { name: 'Adds two values', args: [8, 2, '+'], expected: 10, visible: true },
      { name: 'Divides two values', args: [8, 2, '/'], expected: 4, visible: true },
      { name: 'Subtracts values', args: [3, 8, '-'], expected: -5, visible: false },
      { name: 'Multiplies decimal values', args: [2.5, 4, '*'], expected: 10, visible: false },
      { name: 'Handles division by zero', args: [8, 0, '/'], expected: null, visible: false },
      { name: 'Handles an unsupported operator', args: [8, 2, '%'], expected: null, visible: false },
    ],
  }),
  pythonProject({
    id: 'number-guessing-game', slug: 'number-guessing-game', title: 'Number Guessing Game',
    description: 'Implement the decision-making logic at the heart of a number guessing game.',
    why: 'Guessing games make comparisons and branching tangible without adding unpredictable input or randomness to validation.',
    moduleName: 'number_guessing_game', estimatedMinutes: 25,
    skills: ['Functions', 'Conditionals', 'Comparisons', 'Basic game logic'],
    learningObjectives: ['Compare two numeric values.', 'Represent game outcomes with clear return values.', 'Order conditional branches correctly.'],
    instructions: 'Implement evaluate_guess. Return "too_low", "too_high", or "correct" by comparing guess with secret.',
    requirements: ['Return "correct" when the values are equal.', 'Return "too_low" when guess is below secret.', 'Return "too_high" when guess is above secret.', 'Use only the supplied numeric inputs; do not generate a random number or call input().'],
    example: { input: '50, 30', output: '"too_low"' },
    functionDefinition: { name: 'evaluate_guess', parameters: ['secret', 'guess'], returns: 'str' },
    starterCode: 'def evaluate_guess(secret, guess):\n    """Compare the guess with the secret number."""\n    # TODO: implement the comparison logic\n',
    tests: [
      { name: 'Recognizes a low guess', args: [50, 30], expected: 'too_low', visible: true },
      { name: 'Recognizes the correct guess', args: [50, 50], expected: 'correct', visible: true },
      { name: 'Recognizes a high guess', args: [50, 70], expected: 'too_high', visible: false },
      { name: 'Handles negative values', args: [-10, -20], expected: 'too_low', visible: false },
      { name: 'Compares decimal values', args: [2.5, 2.6], expected: 'too_high', visible: false },
    ],
  }),
  pythonProject({
    id: 'unit-converter', slug: 'unit-converter', title: 'Unit Converter',
    description: 'Create a reusable metric length converter for millimeters, centimeters, meters, and kilometers.',
    why: 'Unit conversion demonstrates how one shared representation can keep arithmetic and mapping logic simple.',
    moduleName: 'unit_converter', estimatedMinutes: 35,
    skills: ['Functions', 'Arithmetic', 'Dictionaries', 'Validation'],
    learningObjectives: ['Use a mapping to represent conversion factors.', 'Convert through a shared base unit.', 'Reject unsupported units safely.'],
    instructions: 'Implement convert for mm, cm, m, and km. Convert through meters and return None when either unit is unsupported.',
    requirements: ['Support millimeters (mm), centimeters (cm), meters (m), and kilometers (km).', 'Support conversion in either direction.', 'Return the original numeric value when units match.', 'Return None for unsupported units.'],
    example: { input: '1000, "m", "km"', output: '1.0' },
    functionDefinition: { name: 'convert', parameters: ['value', 'from_unit', 'to_unit'], returns: 'number | None' },
    starterCode: 'def convert(value, from_unit, to_unit):\n    """Convert a metric length between mm, cm, m, and km."""\n    # TODO: implement the conversion logic\n',
    tests: [
      { name: 'Converts meters to kilometers', args: [1000, 'm', 'km'], expected: 1, visible: true },
      { name: 'Converts centimeters to meters', args: [250, 'cm', 'm'], expected: 2.5, visible: true },
      { name: 'Converts kilometers to millimeters', args: [0.002, 'km', 'mm'], expected: 2000, visible: false },
      { name: 'Keeps matching units unchanged', args: [3.75, 'm', 'm'], expected: 3.75, visible: false },
      { name: 'Handles an unsupported source unit', args: [1, 'mile', 'km'], expected: null, visible: false },
      { name: 'Handles an unsupported target unit', args: [1, 'm', 'yard'], expected: null, visible: false },
    ],
  }),
  pythonProject({
    id: 'expense-tracker', slug: 'expense-tracker', title: 'Expense Tracker',
    description: 'Build a small expense summary from a list of category and amount records.',
    why: 'Expense data provides a practical introduction to traversing records and calculating useful totals.',
    moduleName: 'expense_tracker', estimatedMinutes: 45,
    skills: ['Lists', 'Dictionaries', 'Loops', 'Functions', 'Aggregation'],
    learningObjectives: ['Read values from structured records.', 'Accumulate an overall total.', 'Group and total expenses by category.'],
    instructions: 'Implement summarize_expenses. Return a dictionary with "total" and "by_category" totals without modifying the input list.',
    requirements: ['Add every expense amount to total.', 'Aggregate amounts under their category in by_category.', 'Return {"total": 0, "by_category": {}} for an empty list.', 'Preserve decimal amounts and do not modify the supplied records.'],
    example: { input: '[{"category": "food", "amount": 250}, {"category": "travel", "amount": 100}, {"category": "food", "amount": 150}]', output: '{"total": 500, "by_category": {"food": 400, "travel": 100}}' },
    functionDefinition: { name: 'summarize_expenses', parameters: ['expenses'], returns: 'dict' },
    starterCode: 'def summarize_expenses(expenses):\n    """Return overall and per-category expense totals."""\n    # TODO: implement the expense summary logic\n',
    tests: [
      { name: 'Summarizes several expenses', args: [[{ category: 'food', amount: 250 }, { category: 'travel', amount: 100 }, { category: 'food', amount: 150 }]], expected: { total: 500, by_category: { food: 400, travel: 100 } }, visible: true },
      { name: 'Handles an empty expense list', args: [[]], expected: { total: 0, by_category: {} }, visible: true },
      { name: 'Preserves decimal totals', args: [[{ category: 'food', amount: 12.5 }, { category: 'food', amount: 7.75 }, { category: 'travel', amount: 2 }]], expected: { total: 22.25, by_category: { food: 20.25, travel: 2 } }, visible: false },
      { name: 'Handles one expense', args: [[{ category: 'books', amount: 30 }]], expected: { total: 30, by_category: { books: 30 } }, visible: false },
    ],
  }),
  pythonProject({
    id: 'contact-book', slug: 'contact-book', title: 'Contact Book',
    description: 'Create the core add, find, and remove operations for an in-memory contact book.',
    why: 'A contact book introduces CRUD-style thinking with a familiar dictionary instead of a database or interface.',
    moduleName: 'contact_book', estimatedMinutes: 50,
    skills: ['Dictionaries', 'Functions', 'CRUD concepts', 'Searching', 'Updating data'],
    learningObjectives: ['Add and update dictionary entries.', 'Look up values safely.', 'Remove entries without crashing when they are missing.'],
    instructions: 'Implement manage_contact. For "add" and "remove", update and return contacts. For "get", return the saved phone or None.',
    requirements: ['Support the actions "add", "get", and "remove".', 'An add with an existing name replaces its phone number.', 'Add and remove return the updated contacts dictionary.', 'Missing get and remove operations return None.', 'Unsupported actions return None.', 'Update the supplied contacts dictionary for add and remove operations.'],
    example: { input: '{"Avi": "9876543210"}, "get", "Avi"', output: '"9876543210"' },
    functionDefinition: { name: 'manage_contact', parameters: ['contacts', 'action', 'name', 'phone=None'], returns: 'dict | str | None' },
    starterCode: 'def manage_contact(contacts, action, name, phone=None):\n    """Add, get, or remove an in-memory contact."""\n    # TODO: implement the contact operation\n',
    tests: [
      { name: 'Adds a new contact', args: [{}, 'add', 'Avi', '9876543210'], expected: { Avi: '9876543210' }, visible: true },
      { name: 'Finds an existing contact', args: [{ Avi: '9876543210' }, 'get', 'Avi'], expected: '9876543210', visible: true },
      { name: 'Updates a duplicate name', args: [{ Avi: '1111111111' }, 'add', 'Avi', '9999999999'], expected: { Avi: '9999999999' }, visible: false },
      { name: 'Removes an existing contact', args: [{ Avi: '9876543210' }, 'remove', 'Avi'], expected: {}, visible: false },
      { name: 'Handles a missing contact', args: [{}, 'get', 'Missing'], expected: null, visible: false },
      { name: 'Handles an unsupported action', args: [{ Avi: '9876543210' }, 'rename', 'Avi'], expected: null, visible: false },
    ],
  }),
]);
