import { useEffect, useRef, useState } from 'react';
import { Bot, LoaderCircle, Sparkles } from 'lucide-react';
import { ACCESS_FEATURES, canAccessFeature } from '../../access/accessPolicy';
import { PremiumGate } from '../../access/PremiumGate';
import { useOptionalSubscriptionAccess } from '../../access/SubscriptionAccessContext';
import { projectAIClient } from '../ai/ProjectAIClient';
export { PROJECT_AI_SELECTION_TYPES, createProjectAIContext } from '../ai/projectAIContext';
export function ProjectContextualAI({ context, client = projectAIClient, accessTier }) {
  const access = useOptionalSubscriptionAccess(); const tier = accessTier ?? access?.tier ?? 'FREE'; const empty = { phase: 'idle', questions: [], selected: null, answer: '', followUps: [], conversation: [], error: '' };
  const [state, setState] = useState(empty); const request = useRef(null); const contextKey = JSON.stringify(context ?? null);
  useEffect(() => { request.current?.abort(); setState(empty); }, [contextKey]); useEffect(() => () => request.current?.abort(), []);
  if (!canAccessFeature({ tier, feature: ACCESS_FEATURES.AI_TUTOR })) return <PremiumGate context="Project AI Mentor" />;
  const generate = async () => { if (!context?.selectedContent?.trim()) return; request.current?.abort(); const controller = new AbortController(); request.current = controller; setState((value) => ({ ...value, phase: 'questions-loading', error: '' })); try { const result = await client.generateQuestions(context, { signal: controller.signal }); setState({ ...empty, phase: 'questions', questions: result.questions }); } catch (error) { if (error.name !== 'AbortError') setState((value) => ({ ...value, phase: 'error', error: error.message || 'The AI Mentor is unavailable.' })); } };
  const choose = async (question) => { request.current?.abort(); const controller = new AbortController(); request.current = controller; const history = state.conversation; setState((value) => ({ ...value, phase: 'answer-loading', selected: question, answer: '', followUps: [], error: '' })); try { const result = await client.answer(context, question, history, { signal: controller.signal }); setState((value) => ({ ...value, phase: 'answer', answer: result.answer, followUps: result.followUps, conversation: [...history, { question: question.label, answer: result.answer }].slice(-3), error: '' })); } catch (error) { if (error.name !== 'AbortError') setState((value) => ({ ...value, phase: 'error', error: error.message || 'The AI Mentor is unavailable.' })); } };
  const loading = state.phase.endsWith('loading');
  return <section className="project-contextual-ai" aria-label="Contextual project AI" aria-busy={loading}><Bot aria-hidden="true" /><h2>Contextual AI Mentor</h2>{!context ? <><p>Select guide text, guide code, your code, or terminal output to ask a focused question.</p><span className="project-ai-selection-state">No context selected</span></> : <><div className="project-ai-context-preview"><strong>{context.selectionType.replaceAll('_', ' ')}</strong><pre>{context.selectedContent}</pre></div>{state.phase === 'idle' ? <button className="button button--primary" type="button" onClick={generate}><Sparkles /> Ask AI</button> : null}{loading ? <div className="project-ai-loading" role="status"><LoaderCircle className="is-spinning" /> {state.phase === 'questions-loading' ? 'Generating relevant questions…' : 'Preparing a focused answer…'}</div> : null}{state.questions.length ? <div className="project-ai-options" aria-label="Generated questions">{state.questions.map((question) => <button type="button" disabled={loading} onClick={() => choose(question)} key={question.id}>{question.label}</button>)}</div> : null}{state.selected ? <div className="project-ai-selected"><strong>{state.selected.label}</strong></div> : null}{state.answer ? <article className="project-ai-answer"><p>{state.answer}</p></article> : null}{state.followUps.length ? <div className="project-ai-options" aria-label="Follow-up questions">{state.followUps.map((question) => <button type="button" onClick={() => choose(question)} key={question.id}>{question.label}</button>)}</div> : null}{state.error ? <div className="project-ai-error" role="alert">{state.error}</div> : null}</>}<small>No free-form composer. Context is limited to this selection and checkpoint.</small></section>;
}
