import { useEffect, useState } from 'react';
import { ArrowLeft, Check } from 'lucide-react';
import { Dialog } from '../../components/Dialog';
import { listProjectRuntimes } from '../runtime/projectRuntimeRegistry';

export function ProjectStartDialog({ open, project, initialLanguageId, onClose, onConfirm }) {
  const [languageId, setLanguageId] = useState(initialLanguageId ?? project.supportedLanguages[0]);
  const [step, setStep] = useState('language');
  const [displayName, setDisplayName] = useState(project.title);
  const [error, setError] = useState('');
  useEffect(() => { if (open) { setLanguageId(initialLanguageId ?? project.supportedLanguages[0]); setStep('language'); setDisplayName(project.title); setError(''); } }, [initialLanguageId, open, project]);
  const runtimes = listProjectRuntimes(project);
  const selected = runtimes.find(({ id }) => id === languageId);
  const submitName = () => { const name = displayName.trim(); if (!name) { setError('Project name is required.'); return; } if (name.length > 80 || /[\u0000-\u001f\u007f]/.test(name)) { setError('Use 80 characters or fewer without control characters.'); return; } setDisplayName(name); setStep('confirm'); };
  const title = step === 'language' ? 'Choose your project language' : step === 'name' ? 'Name your project' : 'Confirm project';
  return <Dialog open={open} title={title} description={step === 'name' ? 'Choose the learner-facing name shown in your workspace and download.' : step === 'confirm' ? 'This language becomes active for this project.' : 'The same project guide adapts to the runtime you choose.'} onClose={onClose} className="project-start-dialog">
    {step === 'language' ? <><div className="project-start-languages" role="radiogroup" aria-label="Supported project languages">{runtimes.map((runtime) => <button data-autofocus={runtime.id === languageId ? '' : undefined} type="button" role="radio" aria-checked={runtime.id === languageId} className={runtime.id === languageId ? 'is-selected' : ''} onClick={() => setLanguageId(runtime.id)} key={runtime.id}><span><strong>{runtime.displayName}</strong><small>{runtime.runtime} · {runtime.entrypoint}</small></span>{runtime.id === languageId ? <Check aria-hidden="true" /> : null}</button>)}</div><div className="project-start-actions"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="button" onClick={() => setStep('name')}>Continue</button></div></> : step === 'name' ? <form className="project-name-form" onSubmit={(event) => { event.preventDefault(); submitName(); }}><label htmlFor="project-display-name">Project name</label><input id="project-display-name" data-autofocus value={displayName} maxLength="80" aria-describedby="project-name-help project-name-error" aria-invalid={Boolean(error)} onChange={(event) => { setDisplayName(event.target.value); setError(''); }} /><small id="project-name-help">This name appears in your workspace and project download.</small>{error ? <p id="project-name-error" role="alert">{error}</p> : null}<div className="project-start-actions"><button className="button button--secondary" type="button" onClick={() => setStep('language')}><ArrowLeft /> Back</button><button className="button button--primary" type="submit">Continue</button></div></form> : <><div className="project-language-warning"><strong>{displayName}</strong><p>{selected?.displayName} will be locked for this active project. Changing language later resets checkpoint progress and workspace files.</p></div><div className="project-start-actions"><button className="button button--secondary" type="button" onClick={() => setStep('name')}><ArrowLeft /> Back</button><button className="button button--primary" type="button" onClick={() => onConfirm(languageId, displayName)}>Start Project</button></div></>}
  </Dialog>;
}
