import { useEffect, useState } from 'react';
import { Dialog } from '../components/Dialog.jsx';
import { createCompilerShare, publicShareUrl, sendCompilerFeedback } from './standaloneCompilerApi.js';

export function StandaloneSettingsDialog({ open,onClose,preferences }) { const {preferences:value,update,reset}=preferences; return <Dialog open={open} title="Editor Settings" onClose={onClose} className="standalone-tool-dialog"><div className="standalone-settings-fields"><label>Appearance<select value={value.appearance} onChange={(e)=>update('appearance',e.target.value)}><option value="follow-app">Follow application</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Font size<select value={value.fontSize} onChange={(e)=>update('fontSize',Number(e.target.value))}>{Array.from({length:13},(_,i)=>i+12).map((size)=><option value={size} key={size}>{size}px</option>)}</select></label><label>Tab size<select value={value.tabSize} onChange={(e)=>update('tabSize',Number(e.target.value))}>{[2,4,8].map((size)=><option value={size} key={size}>{size} spaces</option>)}</select></label><label className="standalone-checkbox"><input type="checkbox" checked={value.wordWrap} onChange={(e)=>update('wordWrap',e.target.checked)} />Word wrap</label></div><div className="standalone-dialog-actions"><button className="button button--secondary" type="button" onClick={reset}>Reset to defaults</button><button className="button button--primary" type="button" onClick={onClose}>Done</button></div></Dialog>; }

export function StandaloneFeedbackDialog({ open,onClose,context }) { const [type,setType]=useState('bug');const [description,setDescription]=useState('');const [notice,setNotice]=useState('');const [sending,setSending]=useState(false);const send=async()=>{if(!description.trim())return;setSending(true);setNotice('');try{await sendCompilerFeedback({type,description,languageId:context.languageId,route:window.location.pathname,context});setNotice('Thanks — your feedback was sent.');setDescription('');}catch(error){setNotice(error.message);}finally{setSending(false);}};return <Dialog open={open} title="Send Feedback" onClose={onClose} className="standalone-tool-dialog"><fieldset className="standalone-feedback-types"><legend>Feedback type</legend>{[['bug','Report a bug'],['improvement','Suggest an improvement'],['general','General feedback']].map(([id,label])=><label key={id}><input type="radio" name="feedback-type" checked={type===id} onChange={()=>setType(id)} />{label}</label>)}</fieldset><label className="standalone-feedback-description">Description<textarea required value={description} onChange={(e)=>setDescription(e.target.value)} rows="6" /></label><p className="standalone-privacy-note">Source code and standard input are never attached automatically.</p>{notice?<p role="status">{notice}</p>:null}<div className="standalone-dialog-actions"><button className="button button--secondary" type="button" onClick={onClose}>Cancel</button><button className="button button--primary" type="button" disabled={sending} onClick={send}>{sending?'Sending…':'Send'}</button></div></Dialog>; }

export function StandaloneShareDialog({ open,onClose,languageId,source,stdin }) { const [includeStdin,setIncludeStdin]=useState(false);const [url,setUrl]=useState('');const [notice,setNotice]=useState('');const [creating,setCreating]=useState(false);const [copied,setCopied]=useState(false);useEffect(()=>{if(!open){setIncludeStdin(false);setUrl('');setNotice('');setCreating(false);setCopied(false);}},[open]);const create=async()=>{setCreating(true);setNotice('');try{const result=await createCompilerShare({languageId,source,stdinIncluded:includeStdin,...(includeStdin?{stdin}:{})});setUrl(publicShareUrl(result.shareId));}catch(error){setNotice(error.message);}finally{setCreating(false);}};const copy=async()=>{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800);};return <Dialog open={open} title="Share Code" description="Anyone with this link can view the code." onClose={onClose} className="standalone-tool-dialog"><label className="standalone-checkbox"><input type="checkbox" checked={includeStdin} onChange={(e)=>setIncludeStdin(e.target.checked)} />Include standard input (stdin)</label>{url?<label className="standalone-share-url">Share link<input readOnly value={url} /></label>:null}{notice?<p role="alert">{notice}</p>:null}<div className="standalone-dialog-actions"><button className="button button--secondary" type="button" onClick={onClose}>Close</button>{url?<button className="button button--primary" type="button" onClick={copy}>{copied?'Copied':'Copy link'}</button>:<button className="button button--primary" type="button" disabled={creating} onClick={create}>{creating?'Creating…':'Create link'}</button>}</div></Dialog>; }
